/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 96734CAF-89FE-4FBF-86F6-95C380FFB3C3 instead of MulleFoundation if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark MulleFoundation no-header`
//    rename:              `mulle-sde dependency|library set MulleFoundation include whatever.h`
//    reorder:             `mulle-sde dependency move MulleFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleFoundation [no-]import`
//    toggle public:       `mulle-sde dependency mark MulleFoundation [no-]public`
//    toggle optional:     `mulle-sde dependency mark MulleFoundation [no-]require`
//    remove for platform: `mulle-sde dependency mark MulleFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleFoundation/MulleFoundation.h>   // MulleFoundation

// You can tweak the following #import with these commands.
// (Use 86F449FA-93D6-44FD-B2A4-4A1B858E8CAE instead of MulleObjCExpatFoundation if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark MulleObjCExpatFoundation no-header`
//    rename:              `mulle-sde dependency|library set MulleObjCExpatFoundation include whatever.h`
//    reorder:             `mulle-sde dependency move MulleObjCExpatFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjCExpatFoundation [no-]import`
//    toggle public:       `mulle-sde dependency mark MulleObjCExpatFoundation [no-]public`
//    toggle optional:     `mulle-sde dependency mark MulleObjCExpatFoundation [no-]require`
//    remove for platform: `mulle-sde dependency mark MulleObjCExpatFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>   // MulleObjCExpatFoundation

// You can tweak the following #import with these commands.
// (Use AD2BA78D-47A0-49D4-BE11-56815D2CA5A5 instead of MulleObjCJSMNFoundation if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark MulleObjCJSMNFoundation no-header`
//    rename:              `mulle-sde dependency|library set MulleObjCJSMNFoundation include whatever.h`
//    reorder:             `mulle-sde dependency move MulleObjCJSMNFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjCJSMNFoundation [no-]import`
//    toggle public:       `mulle-sde dependency mark MulleObjCJSMNFoundation [no-]public`
//    toggle optional:     `mulle-sde dependency mark MulleObjCJSMNFoundation [no-]require`
//    remove for platform: `mulle-sde dependency mark MulleObjCJSMNFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCJSMNFoundation/MulleObjCJSMNFoundation.h>   // MulleObjCJSMNFoundation

#ifdef __has_include
# if __has_include( "_mulle-pq-include.h")
#  include "_mulle-pq-include.h"
# endif
#endif

